Beau fyupdates
djsir-data/creative pull request #18
Opened 2023-02-10 00:26 UTC by beaudjpr

Adding accessibility features, and applying other minor fixes

2023-02-10 06:08 UTC, mrjoh3 requested changes
main things are to remove the `quick_iframe` functionfrom each file and make sure the output files aren't called `test` or `version`. Can you also update the rmd file names. there is no longer any reason to include `version2` in the file names.

2023-02-10 06:08 UTC, mrjoh3 commented on inst/docs/landing.Rmd
>                                 output_file = here::here(IFRAME_FOLD,
didn't we update this variable name? Variable names like this should also be defined in `setup.Rmd` as they are the same for each file. It is best to only define these variables in one place.

2023-02-10 06:08 UTC, mrjoh3 commented on inst/docs/setup.Rmd
> +IFRAME_FOLD <- here::here('docs') # OUTPUT_FOLDER
sorry, I know I'm being pedantic, but iframes are only in the host website. This folder holds content that is consumed by the iframes. Please update to `OUTPUT_FOLDER` or `CONTENT_FOLDER` and make sure this variable is only defined here,

2023-02-10 06:08 UTC, mrjoh3 commented on inst/docs/setup.Rmd
> +                    output_file = glue('test_{outfile}'),
why have we added `test_` it is not needed

2023-02-22 01:00 UTC, Henry-DJPR approved these changes

2023-02-22 01:00 UTC, merged